export const toppings = [
  { name: "Pepporoni" },
  { name: "Sausage" },
  { name: "Chicken" },
  { name: "Peppers" },
  { name: "Mushrooms" },
  { name: "Bacon" },
  { name: "ExtraCheese" },
  { name: "Red Peppers" },
  { name: "Chicken Fries" },
  { name: "Green pepper" },
  { name: "Fresh garlic" },
  { name: "Fresh basil" },
  { name: "Green pepper" },
  { name: "Black olives" },
  { name: "Roasted Butternut Squash" },
  { name: "Roasted Broccoli" },
  { name: "Roasted Fennel" },
  { name: "Roasted Cauliflower" },
  { name: "Veggie sausage" },
  { name: "Pickled Jalapeños" },
];
